SELECT DISTINCT LastName,FirstName,Phone
FROM CUSTOMER JOIN INVOICE
ON CustomerID IN (SELECT CustomerNumber FROM INVOICE,INVOICE_ITEM
WHERE Item = 'Dress Shirt' AND INVOICE.InvoiceNumber = INVOICE_ITEM.InvoiceNumber)
ORDER BY LastName ASC, FirstName DESC;