SELECT CUSTOMER.LastName, CUSTOMER.FirstName,
CUSTOMER.Phone
FROM (CUSTOMER JOIN INVOICE
ON CUSTOMER.CustomerID = INVOICE.CustomerNumber)
JOIN INVOICE_ITEM ON INVOICE.InvoiceNumber = INVOICE_ITEM.InvoiceNumber
WHERE INVOICE_ITEM.Item='Dress Shirt';